# Generated by Django 5.2.14 on 2026-05-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('precision_obtenida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('registros_usados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descartado', 'Descartado')], default='activo', max_length=20)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Modelo IA',
                'verbose_name_plural': 'Modelos IA',
            },
        ),
        migrations.CreateModel(
            name='PrediccionZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.sector')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.tipodelito')),
            ],
            options={
                'verbose_name': 'Predicción de Zona',
                'verbose_name_plural': 'Predicciones de Zonas',
                'ordering': ['-fecha'],
            },
        ),
    ]
