# Generated by Django 5.2.14 on 2026-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='incidentes/')),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('falso', 'Falso')], default='pendiente', max_length=20)),
                ('fecha_hora_validacion', models.DateTimeField(blank=True, null=True)),
                ('num_testigos', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='OperativoPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('num_agents', models.IntegerField(default=1)),
                ('zona_asignada', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operativo Policial',
                'verbose_name_plural': 'Operativos Policiales',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('centro_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('centro_lon', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='Testigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_origen', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('voz', 'Voz'), ('telegram', 'Telegram')], default='web', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testigo',
                'verbose_name_plural': 'Testigos',
            },
        ),
        migrations.CreateModel(
            name='TipoDelito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Delito',
                'verbose_name_plural': 'Tipos de Delito',
            },
        ),
    ]
