# Generated by Django 5.2.14 on 2026-05-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='reporte_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operativopolicial',
            name='policia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operativopolicial',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.sector'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.sector'),
        ),
        migrations.AddField(
            model_name='testigo',
            name='incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testigos', to='incidentes.incidente'),
        ),
        migrations.AddField(
            model_name='testigo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.tipodelito'),
        ),
    ]
