# Generated by Django 5.2.14 on 2026-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='reporte_anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
