# Generated by Django 5.2.14 on 2026-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_incidente_reporte_anonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testigo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testigo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='testigos/'),
        ),
    ]
