# Generated by Django 5.2.14 on 2026-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0004_testigo_comentario_testigo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='testigo',
            name='reporte_anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
