# Generated by Django 5.2.14 on 2026-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_preferido', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('ambos', 'Ambos')], default='ambos', max_length=20)),
                ('recibir_predictivas', models.BooleanField(default=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción a Alertas',
                'verbose_name_plural': 'Suscripciones a Alertas',
            },
        ),
    ]
