# Generated by Django 5.2.14 on 2026-05-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('incidentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerta',
            name='incidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.incidente'),
        ),
        migrations.AddField(
            model_name='suscripcionalerta',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.sector'),
        ),
        migrations.AddField(
            model_name='suscripcionalerta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_alertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='suscripcionalerta',
            unique_together={('usuario', 'sector')},
        ),
    ]
